dependencies:
  - python=3.8
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - torch==1.11.0+cu113
      - torchvision==0.12.0+cu113
      - pytorch-lightning==1.4.*
      - piq
      - albumentations
      - pandas
      - tqdm
